// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.Api.Database;

#nullable disable

namespace WebApplication3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250404194010_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63); // PostgreSQL max identifier length

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder); 
            modelBuilder.Entity("Products.Api.Entities.Products", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid") // PostgreSQL type for GUID
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("Createdat")
                        .HasColumnType("timestamp with time zone") // PostgreSQL type for DateTimeOffset
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text") // PostgreSQL type for text
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text") // PostgreSQL type for text
                        .HasColumnName("name");

                    b.Property<string>("Ski")
                        .IsRequired()
                        .HasColumnType("text") // PostgreSQL type for text
                        .HasColumnName("ski");

                    b.Property<Guid>("Subcategory")
                        .HasColumnType("uuid") // PostgreSQL type for GUID
                        .HasColumnName("subcategory_id");

                    b.Property<DateTimeOffset>("Updatedat")
                        .HasColumnType("timestamp with time zone") // PostgreSQL type for DateTimeOffset
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("Products.Api.Entities.SubCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid") // PostgreSQL type for GUID
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid") // PostgreSQL type for GUID
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text") // PostgreSQL type for text
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("Created_at")
                        .HasColumnType("timestamp with time zone") // PostgreSQL type for DateTimeOffset
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text") // PostgreSQL type for text
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("Updated_at")
                        .HasColumnType("timestamp with time zone") // PostgreSQL type for DateTimeOffset
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("subcategory");
                });
#pragma warning restore 612, 618
        }
    }
}
